/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AuditLogTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChatConversationsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChatMessagesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NotificationDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NotificationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NotificationWebSocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "SocialBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}

import "sst"
export {}